"""Draw images/chamber_bulge.svg from the reproduced contour. Run: python3 simulations/chamber_bulge/gen_bulge.py"""
import math, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from contour import make
f,z_hi,L,r_t,V=make(0.075)
S=78.0; X0=110; YC=330
def X(z): return X0+S*z
def Yu(r): return YC-S*r
def Yl(r): return YC+S*r
N=400
zs=[z_hi*i/N for i in range(N+1)]; zs[-1]=z_hi-1e-9
def slope(z,h=1e-4): return (f(min(z+h,z_hi-1e-9))-f(max(z-h,0)))/(2*h)
def wrap_mm(z):
    if z<0.7: return 140
    if z<1.4: return 132
    if z<2.8: return 95
    if z<5.8: return 152
    return 78
EX=2.0
def outer(z,sign):
    r=f(z); s=slope(z); n=math.hypot(1,s)
    t=wrap_mm(z)/1000*EX
    # outward normal in (z,r): (-s,1)/n
    return z-s*t/n*0, r+t/n, z - (s*t/n), r + t/n
inner_u=" ".join(f"{X(z):.1f},{Yu(f(z)):.1f}" for z in zs)
inner_l=" ".join(f"{X(z):.1f},{Yl(f(z)):.1f}" for z in zs)
def band(sign):
    pts_in=[(X(z),YC-sign*S*f(z)) for z in zs]
    pts_out=[]
    for z in zs:
        r=f(z); s=slope(z); n=math.hypot(1,s); t=wrap_mm(z)/1000*EX
        zo=z - s*t/n; ro=r + t/n
        pts_out.append((X(zo),YC-sign*S*ro))
    poly=pts_in+pts_out[::-1]
    return " ".join(f"{a:.1f},{b:.1f}" for a,b in poly)
def seg(z0,z1,sign):
    pts=[z for z in zs if z0<=z<=z1]
    return " ".join(f"{X(z):.1f},{YC-sign*S*f(z):.1f}" for z in pts)
hot = [(1.35,2.85,'#D7301F',0.75),(2.85,5.8,'#D7301F',0.95),(7.4,z_hi,'#F08C3A',0.8)]
svg=[]
A=svg.append
A('''<?xml version="1.0" encoding="UTF-8"?>
<!-- The bulged near-term methane chamber, in section through its axis, for the 2.5 kg rod.
     Contour reproduced from puffsat_impact_simulation's sweep --shape-40c / --efficiency-r3:
     vessel_sized(r_c 1.4, head 0.7, 40 m^3 base, 12 deg cone, throat 0.66 m^2 for 2 Hz) plus
     Bulge{dr 1.6, z0 1.4, z1 2.8, ramp 0.5, ramp_out 3.0}: 106 m^3. Generated by a script;
     the chamber and plug are drawn to one scale, the wrap at twice scale.
     Export: inkscape images/chamber_bulge.svg -o images/chamber_bulge.pdf -->
<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
     width="1000" height="790" viewBox="0 0 1000 790">
  <defs>
    <style>
      text { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 15px; fill: #222; }
      .small { font-size: 13.5px; }
      .tiny { font-size: 12px; }
      .title { font-size: 17px; font-weight: bold; }
      .leader { stroke: #888; stroke-width: 1.1; fill: none; }
      .dim { stroke: #333; stroke-width: 1.1; fill: none; }
      .box { fill: #fff; stroke: #999; stroke-width: 1.2; }
    </style>
    <marker id="ar" markerUnits="userSpaceOnUse" markerWidth="10" markerHeight="10" refX="9" refY="5" orient="auto"><path d="M0,1 L10,5 L0,9 Z" fill="#B03A2E"/></marker>
    <marker id="ad" markerUnits="userSpaceOnUse" markerWidth="10" markerHeight="10" refX="9" refY="5" orient="auto"><path d="M0,1 L10,5 L0,9 Z" fill="#333"/></marker>
    <marker id="ad2" markerUnits="userSpaceOnUse" markerWidth="10" markerHeight="10" refX="1" refY="5" orient="auto"><path d="M10,1 L0,5 L10,9 Z" fill="#333"/></marker>
    <linearGradient id="gas" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#FFF4DA"/><stop offset="1" stop-color="#FDE3B8"/></linearGradient>
    <linearGradient id="plug" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#BFD7E6"/><stop offset="0.6" stop-color="#6E9FC0"/><stop offset="1" stop-color="#2F5F86"/></linearGradient>
    <pattern id="wrapp" width="6" height="6" patternUnits="userSpaceOnUse"><rect width="6" height="6" fill="#F3E3A6"/><line x1="0" y1="3" x2="6" y2="3" stroke="#D8C27A" stroke-width="1"/></pattern>
  </defs>
  <rect width="1000" height="790" fill="#ffffff"/>
''')
# gas fill
A(f'  <polygon points="{inner_u} {" ".join(f"{X(z):.1f},{Yl(f(z)):.1f}" for z in zs[::-1])}" fill="url(#gas)"/>')
# wrap bands
for sg in (1,-1):
    A(f'  <polygon points="{band(sg)}" fill="url(#wrapp)" stroke="#B79E52" stroke-width="0.8"/>')
# hot zones
for z0,z1,c,o in hot:
    for sg in (1,-1):
        A(f'  <polyline points="{seg(z0,z1,sg)}" fill="none" stroke="{c}" stroke-width="7" stroke-opacity="{o}" stroke-linecap="round"/>')
# shell
for pts in (inner_u,inner_l):
    A(f'  <polyline points="{pts}" fill="none" stroke="#4A5560" stroke-width="2.4"/>')
# ghost unbulged wall
for sg in (1,-1):
    A(f'  <line x1="{X(0.7):.1f}" y1="{YC-sg*S*1.4:.1f}" x2="{X(4.6):.1f}" y2="{YC-sg*S*1.4:.1f}" stroke="#555" stroke-width="1.4" stroke-dasharray="6,5"/>')
# axis
A(f'  <line x1="{X0-90}" y1="{YC}" x2="{X(z_hi)+120}" y2="{YC}" stroke="#bbb" stroke-width="1" stroke-dasharray="10,4,2,4"/>')
# nozzle start beyond throat (illustrative)
xt=X(z_hi)
for sg in (1,-1):
    A(f'  <path d="M {xt:.1f},{YC-sg*S*r_t:.1f} Q {xt+50:.1f},{YC-sg*S*r_t*1.15:.1f} {xt+110:.1f},{YC-sg*S*r_t*1.9:.1f}" fill="none" stroke="#4A5560" stroke-width="2.2" stroke-dasharray="7,4"/>')
# plug
pr=0.065*S
A(f'  <rect x="{X(0.8):.1f}" y="{YC-pr:.1f}" width="{S*1.5:.1f}" height="{2*pr:.1f}" fill="url(#plug)" stroke="#2F5F86" stroke-width="1"/>')
# rod
A(f'  <line x1="{X0-85}" y1="{YC}" x2="{X0-12}" y2="{YC}" stroke="#333" stroke-width="3" marker-end="url(#ad)"/>')
A(f'  <rect x="{X0-80}" y="{YC-3}" width="{0.69*S:.1f}" height="6" fill="#9DB4C0" stroke="#333" stroke-width="0.8"/>')
# line blast shock fronts (cylinders around the stopping line)
for R in (1.0,2.0):
    for sg in (1,-1):
        A(f'  <line x1="{X(1.45):.1f}" y1="{YC-sg*S*R:.1f}" x2="{X(2.55):.1f}" y2="{YC-sg*S*R:.1f}" stroke="#B03A2E" stroke-width="1.4" stroke-dasharray="4,3"/>')
for zz in (1.7,2.2):
    A(f'  <line x1="{X(zz):.1f}" y1="{YC-pr-4:.1f}" x2="{X(zz):.1f}" y2="{Yu(2.85):.1f}" stroke="#B03A2E" stroke-width="1.6" marker-end="url(#ar)"/>')
A(f'''
  <!-- labels, upper half -->
  <text x="20" y="34" class="title">Bulged methane chamber, 2.5 kg rod (106 m³), to scale</text>
  <path class="leader" d="M {X(0.25):.1f},{Yu(f(0.25))-4:.1f} L {X(0.1):.1f},120"/>
  <text x="20" y="96" class="small">domed head, r 1.4 m,</text>
  <text x="20" y="113" class="small">port at the apex</text>
  <path class="leader" d="M {X(2.1):.1f},{Yu(3.0)-20:.1f} L {X(2.1):.1f},62"/>
  <text x="{X(1.2):.1f}" y="56" class="small">bulge to r 3.0 m beside the plug: wall peaks 0.67 GPa</text>
  <path class="leader" d="M {X(4.1):.1f},{Yu(f(4.1))-14:.1f} L {X(4.6):.1f},104"/>
  <text x="{X(4.4):.1f}" y="88" class="small">3 m taper: the hottest zone, takes the</text>
  <text x="{X(4.4):.1f}" y="104" class="small">downstream-moving remnant; thickest wrap</text>
  <path class="leader" d="M {X(8.2):.1f},{Yu(f(8.2))-8:.1f} L {X(8.4):.1f},190"/>
  <text x="{X(7.0):.1f}" y="164" class="small">12° cone; a later 0.68 GPa hit</text>
  <text x="{X(7.0):.1f}" y="180" class="small">near the throat, ~380 µs</text>
  <path class="leader" d="M {X(3.9):.1f},{Yl(1.4):.1f} L {X(3.7):.1f},{Yl(1.4)+12:.1f}"/>
  <text x="{X(2.45):.1f}" y="{Yl(1.4)+26:.1f}" class="tiny">dashed: the wall with no bulge,</text>
  <text x="{X(2.45):.1f}" y="{Yl(1.4)+41:.1f}" class="tiny">r 1.4 m, takes ~2.2 GPa</text>
  <text x="{X(2.6):.1f}" y="{Yu(1.2):.1f}" class="tiny" fill="#B03A2E">line-blast shock,</text>
  <text x="{X(2.6):.1f}" y="{Yu(1.2)+15:.1f}" class="tiny" fill="#B03A2E">p ∝ (E/L)/R²</text>
  <path class="leader" d="M {xt:.1f},{YC+S*r_t+3:.1f} L {xt+12:.1f},{YC+S*r_t+40:.1f}"/>
  <text x="{xt-20:.1f}" y="{YC+S*r_t+56:.1f}" class="small">throat 0.66 m²</text>
  <text x="{xt+40:.1f}" y="{YC+4:.1f}" class="tiny">to the extension</text>
  <!-- rod and plug -->
  <text x="18" y="{YC-14}" class="small">rod, 75 km/s</text>
  <path class="leader" d="M {X(2.25):.1f},{YC+pr+1:.1f} L {X(2.6)-4:.1f},{YC+24:.1f}"/>
  <text x="{X(2.6):.1f}" y="{YC+28:.1f}" class="small">plug: 10 kg frozen methane in a</text>
  <text x="{X(2.6):.1f}" y="{YC+45:.1f}" class="small">polyethylene can, 1.5 m, densest at the back</text>
  <!-- wrap thickness labels, lower half -->
''')
for z,lab in [(0.35,'140'),(1.12,'132'),(2.1,'95'),(4.3,'152'),(7.3,'78')]:
    r=f(z); t=wrap_mm(z)/1000*EX
    y=Yl(r+t)+18
    A(f'  <text x="{X(z)-12:.1f}" y="{y:.1f}" class="tiny">{lab}</text>')
A(f'''  <text x="{X(1.6):.1f}" y="{Yl(3.0)+52:.1f}" class="small">dry Kevlar 49 wrap, mm by zone, drawn at twice scale</text>
  <!-- dimensions -->
  <line class="dim" x1="{X(9.6):.1f}" y1="{Yu(3.0):.1f}" x2="{X(9.6):.1f}" y2="{Yl(3.0):.1f}" marker-start="url(#ad2)" marker-end="url(#ad)" transform="translate(40,0)"/>
  <line x1="{X(2.8):.1f}" y1="{Yu(3.0):.1f}" x2="{X(9.6)+40:.1f}" y2="{Yu(3.0):.1f}" stroke="#ccc" stroke-dasharray="3,3"/>
  <line x1="{X(2.8):.1f}" y1="{Yl(3.0):.1f}" x2="{X(9.6)+40:.1f}" y2="{Yl(3.0):.1f}" stroke="#ccc" stroke-dasharray="3,3"/>
  <text x="{X(9.6)+46:.1f}" y="{YC-40:.1f}" class="small">6.0 m</text>
  <line class="dim" x1="{X(0):.1f}" y1="{Yl(3.0)+75:.1f}" x2="{X(z_hi):.1f}" y2="{Yl(3.0)+75:.1f}" marker-start="url(#ad2)" marker-end="url(#ad)"/>
  <text x="{X(4.0):.1f}" y="{Yl(3.0)+92:.1f}" class="small">9.0 m port to throat</text>
  <!-- legend and notes -->
  <g transform="translate(20,{Yl(3.0)+112:.1f})">
    <line x1="0" y1="0" x2="34" y2="0" stroke="#D7301F" stroke-width="7" stroke-opacity="0.9"/>
    <text x="42" y="5" class="small">where the solved blast loads the wall hardest (0.25 cm cells)</text>
    <text x="0" y="28" class="small">The steady peak, about 94 bar, is the same everywhere.</text>
    <text x="0" y="46" class="small">Only the microsecond spike varies along the wall.</text>
    <text x="0" y="68" class="small">The 5 kg chamber is this shape grown by 2^(1/3) in every</text>
    <text x="0" y="86" class="small">length: 212 m³, 7.6 m across, the same pressures.</text>
  </g>
  <!-- inset: wall layers -->
  <g transform="translate(690,{Yl(3.0)+104:.1f})">
    <rect x="0" y="0" width="290" height="86" rx="6" class="box"/>
    <text x="10" y="18" class="tiny" font-weight="bold">wall, gas side at left (not to scale)</text>
    <rect x="12" y="28" width="8" height="48" fill="#2B2B2B"/>
    <rect x="20" y="28" width="4" height="48" fill="#7FB6C9"/>
    <rect x="24" y="28" width="18" height="48" fill="#AEB8BF"/>
    <rect x="42" y="28" width="60" height="48" fill="url(#wrapp)" stroke="#B79E52" stroke-width="0.6"/>
    <text x="110" y="38" class="tiny">pitch film</text>
    <text x="110" y="52" class="tiny">alumina barrier, under 1 µm</text>
    <text x="110" y="66" class="tiny">10 mm Cr–Mo shell</text>
    <text x="110" y="80" class="tiny">dry Kevlar 49, unbonded</text>
  </g>
</svg>''')
open(os.path.join(os.path.dirname(os.path.abspath(__file__)),'..','..','images','chamber_bulge.svg'),'w').write("\n".join(svg))
print(z_hi, X(z_hi))
